FROM golang:alpine
WORKDIR /app
ENV TELEGRAM_APITOKEN=YOUR_APITOKEN
ENV OPENAI_API_TOKEN=YOUR_OPENAI_API_TOKEN
ENV USERNAME=YUOR_USERNAME
ENV PASSWORD=YOUR_PASSWORD
ENV MONGO_URI=YOUR_MONGO_URI
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./main.go
CMD ["./main"]
